apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-application
  template:
    metadata:
      labels:
        app: java-application
    spec:
      containers:
      - name: java-application
        image: 590183949406.dkr.ecr.ap-south-1.amazonaws.com/deploy-springapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-db-service:5432/mydb
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: "12345"
