apiVersion: v1
kind: Service
metadata:
  name: java-application-service
spec:
  type: LoadBalancer
  selector:
    app: java-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
